#pragma once

/*
				CODES
	This header includes all of the
	different codes for each of the
	responses and requests in our protocol.
*/

// <-- RESPONSE CODES -->

enum ResponseCodes { ERROR_RESPONSE_CODE = 0, SIGNUP_RESPONSE_CODE = 20, LOGIN_RESPONSE_CODE = 21, LOGOUT_RESPONSE_CODE = 31,
				     GET_ROOMS_RESPONSE_CODE = 23, GET_PLAYERS_IN_ROOMS_RESPONSE_CODE = 22, JOIN_ROOM_RESPONSE_CODE = 32,
					 CREATE_ROOM_RESPONSE_CODE = 42, GET_HIGHSCORE_RESPONSE_CODE = 52, GET_STATISTICS_RESPONSE_CODE = 62,
					 CLOSE_ROOM_RESPONSE_CODE = 33, START_GAME_RESPONSE_CODE = 34, LEAVE_ROOM_RESPONSE_CODE = 35,
					 GET_ROOM_STATE_RESPONSE_CODE = 36, GET_GAME_RESULTS_RESPONSE_CODE = 71, SUBMIT_ANSWER_RESPONSE_CODE = 72,
					 GET_QUESTION_RESPONSE_CODE = 73, LEAVE_GAME_RESPONSE_CODE = 74 };

// <-- REQUEST CODES -->

enum RequestCodes { SIGNUP_REQUEST_CODE = 1, LOGIN_REQUEST_CODE, LOGOUT_REQUEST_CODE, 
					GET_ROOMS_REQUEST_CODE, GET_PLAYERS_IN_ROOMS_REQUEST_CODE, JOIN_ROOM_REQUEST_CODE,
					CLOSE_ROOM_REQUEST_CODE, START_GAME_REQUEST_CODE, LEAVE_ROOM_REQUEST_CODE,
					GET_ROOM_STATE_REQUEST_CODE, CREATE_ROOM_REQUEST_CODE, GET_HIGHSCORE_REQUEST_CODE, 
					GET_STATISTICS_REQUEST_CODE, GET_GAME_RESULTS_REQUEST_CODE, SUBMIT_ANSWER_REQUEST_CODE,
					GET_QUESTION_REQUEST_CODE, LEAVE_GAME_REQUEST_CODE };

// <-- HANDLERS & LOGIN MANAGER -->

#define SUCCESSFUL_LOGIN		99
#define SUCCESSFUL_SIGNUP		100

// <-- INDEXES IN BUFFER -->

#define REQUEST_ID_IN_BUFFER	0
#define DATA_LENGTH_START		1
#define DATA_LENGTH_END			4
#define DATA_START				5

// <-- ROOM CODES -->

enum RoomStatus { ROOM_OPEN = 200, GAME_STARTED, GAME_ENDED };

// <-- GAME CODES -->

enum GameCodes { MORE_QUESTIONS = 90, NO_MORE_QUESTIONS };