#pragma once

/*
				CODES
	This header includes all of the
	different codes for each of the
	responses and requests in our protocol.
*/

// <-- RESPONSE CODES -->

enum ResponseCodes { ERROR_RESPONSE_CODE = 0, SIGNUP_RESPONSE_CODE = 11, LOGIN_RESPONSE_CODE = 21, LOGOUT_RESPONSE_CODE = 31,
				     GET_ROOMS_RESPONSE_CODE = 12, GET_PLAYERS_IN_ROOMS_RESPONSE_CODE = 22, JOIN_ROOM_RESPONSE_CODE = 32,
					 CREATE_ROOM_RESPONSE_CODE = 42, GET_HIGHSCORE_RESPONSE_CODE = 52, GET_STATISTICS_RESPONSE_CODE = 62};

// <-- REQUEST CODES -->

enum RequestCodes { SIGNUP_REQUEST_CODE = 1, LOGIN_REQUEST_CODE, LOGOUT_REQUEST_CODE, 
					GET_ROOMS_REQUEST_CODE, GET_PLAYERS_IN_ROOMS_REQUEST_CODE, JOIN_ROOM_REQUEST_CODE,
					CREATE_ROOM_REQUEST_CODE, GET_HIGHSCORE_REQUEST_CODE, GET_STATISTICS_REQUEST_CODE};

// <-- HANDLERS & LOGIN MANAGER -->

#define SUCCESSFUL_LOGIN		99
#define SUCCESSFUL_SIGNUP		100

// <-- INDEXES IN BUFFER -->

#define REQUEST_ID_IN_BUFFER	0
#define DATA_LENGTH_START		1
#define DATA_LENGTH_END			4
#define DATA_START				5

// <-- ROOM CODES -->

enum RoomStatus { ROOM_OPEN = 200 };